version: '3'
volumes:
   db-data:
     driver: "local"
services:
  go-web:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
  db:
    build: ./docker/local-db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
    volumes:
      - "db-data:/var/lib/postgresql/data"