output = "src/app/models"
[psql]
  dbname = "localdb"
  host   = "127.0.0.1"
  port   = 5432
  user   = "postgres"
  pass   = "mysecretpassword1234"
  sslmode = "disable"
  blacklist = ["migrations", "other"]